#!/bin/bash


## preparation
if [[ -d "./public" ]];then
    rm -fr ./public
fi

if [[ -d "./remote/public" ]];then
    rm -fr ./remote/public
fi


## talwind generator
themes=$(jq '.theme' config/_default/params.json | sed -e 's/^"//' -e 's/"$//' )
twstat=$(jq '.tailwind' themes/$themes/assets/model/base/config.json | sed -e 's/^"//' -e 's/"$//' )

if [[ $twstat -eq "true" ]];then
    tailpt=./assets/_core/script/vendor/tailwind
    tailwindcss -c $tailpt/tailwind.config.js -i $tailpt/input.css  -o $tailpt/output.css
fi


hugo &&

echo "" > $tailpt/output.css
