#!/bin/bash

if [[ -d "public" ]];then
    rm -fr public
fi


themes=$(jq '.theme' config/_default/params.json | sed -e 's/^"//' -e 's/"$//' )
twstat=$(jq '.tailwind' themes/$themes/assets/model/base/config.json | sed -e 's/^"//' -e 's/"$//' )
tailpt=./assets/_core/script/vendor/tailwind

if [[ $twstat -eq "true" ]];then
    
    tailwindcss -c $tailpt/tailwind.config.js -i $tailpt/input.css  -o $tailpt/output.css
fi


hugo &&

echo "" > $tailpt/output.css
